version: '3.8'

services:
  serverbot-postgres:
    restart: always
    env_file:
      - stack.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
        ]
      interval: 5s
      timeout: 10s
      retries: 3

  discord-bot:
    restart: always
    image: kelliedev/serverbot:latest
    env_file:
      - stack.env
    expose:
      - 9090 
    ports:
      - 9090:9090